postgres:
  host: localhost
  port: 5432
  user: datkan_user
  password: password
  dbname: dbatkanai
  sslmode: disable
  timezone: UTC
  max_open_conns: 20
  max_idle_conns: 5
  conn_max_lifetime: 15m
